name: CI-Main

# Controls when the action will run

on:
  # Allows you to run this workflow manually from the actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that ca run sequentially or in parallel
jobs:

